INSERT INTO users (user_name, user_email, user_password, user_image)
VALUES
('Sylvia Palmer', 'spalmer@gmail.com', '12345', 'https://i.imgur.com/LpaY82x.png'),
('Terrence Malcolm', 'tmalcolm@gmail.com', '12345', 'https://i.imgur.com/Nmx0Qxo.png'),
('Mildred Nazir', 'mnazir@gmail.com', '12345', 'https://i.imgur.com/T2WwVfS.png'),
('Charles Roy', 'croy@gmail.com', '12345', 'https://i.imgur.com/FK8V841.jpg'),
('Sven Jones', 'sjones@gmail.com', '12345', 'https://i.imgur.com/twYrpay.jpg'),
('Susan Reynolds', 'sreynolds@gmail.com', '12345', 'https://i.imgur.com/TdOAdde.jpg'),
('Alec Quon', 'aquon@gmail.com', '12345', 'https://i.imgur.com/3tVgsra.jpg'),
('Viktor Jain', 'vjain@gmail.com', '12345', 'https://i.imgur.com/iHq8K8Z.jpg'),
('Liam Chu', 'lchu@gmail.com', '12345', 'https://i.imgur.com/nPywAp1.jpg'),
('Sam Stanic', 'sstanic@gmail.com', '12345', 'https://i.imgur.com/okB9WKC.jpg');

INSERT INTO items (item_name, item_location, item_base_price, item_status, item_image_1, item_image_2, item_image_3, item_image_4, item_description, owner_id) 
VALUES 
('Swingline Stapler', 'Milton, ON', 450, true, 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Stapler picture', 'LightTouch Reduced Effort Stapler simplifies stapling two to 20 sheets. Stapler is engineered for smooth, easy operation, and excels at low sheet counts. For best performance, use Swingline S.F. 4 Premium Staples. Full-strip stapler design accommodates full strip of 210 staples. Soft grip surfaces enhance feel and control for desktop or handheld use. Made with a durable plastic housing and metal mechanism.', 1),
('Multifunctional Kitchen Scissors', 'Milton, ON', 500, false, 'Scissors picture', 'Scissors picture', 'Scissors picture', 'Scissors picture', 'Kitchen scissors are made of high-quality 3CR14 stainless steel, corrosion resistant, really sharp and durable, for cutting meat, chicken, poultry, fruits, fish scale, vegetables, herbs and so on', 1),
('Asvine Pen', 'Milton, ON', 100, true, 'Pen picture', 'Pen picture', 'Pen picture', 'Pen picture', 'These fresh, elegant, reliable forest series fountain pen by Asvine is a true marriage of the sophistication of finer days with the latest technology of modern times. Hand assembled and checked for flawless quality, it gives high precision and exceptional writing comfort for every occasion, coupled with a gorgeous design. With this pen in your possession, clients, colleagues, and friends will know you for your taste, class, and sophistication.', 1),
('Craftsman Measuring Tape', 'Victoria, BC', 200, false, 'Measuring Tape picture', 'Measuring Tape picture', 'Measuring Tape picture', 'Measuring Tape picture', 'Measure twice, cut once, and rely on Craftsman tapes for fast and accurate measurements. Our self lock tape measures feature blades that automatically stay in a locked position until you press a button to retract them. The auto-locking feature offers smooth, comfortable retraction to avoid having the hook slam into the case, which makes the tapes both user friendly and longer lasting. Fractions are printed on the blade to make taking measurements easier than ever before, making this the perfect tape measure for new homeowners or avid DIYers.', 2),
('Lighter', 'Victoria, BC', 200, true, 'Lighter picture', 'Lighter picture', 'Lighter picture', 'Lighter picture', 'Just charge it and your good to go!', 2),
('Ipad', 'Victoria, BC', 1500, true, 'Ipad picture', 'Ipad picture', 'Ipad picture', 'Ipad picture', 'Brand new Ipad', 2),
('Speakers', 'Couborg, ON', 700, true, 'Speakers picture', 'Speakers picture', 'Speakers picture', 'Speakers picture', 'A high-quality speakers', 3),
('Calculator', 'Couborg, ON', 400, true, 'Calculator picture', 'Calculator picture', 'Calculator picture', 'Calculator picture', 'Amazing calculator that has a Sine, Cosine, and Tan buttons', 3),
('Battery Bank', 'Couborg, ON', 700, false, 'Battery Bank picture', 'Battery Bank picture', 'Battery Bank picture', 'Battery Bank picture', 'Good for extra battery during hikes', 3),
('SDD Hard drive', 'Chatham-Kent, ON', 400, false, 'SDD Hard Drive picture', 'SDD Hard Drive picture', 'SDD Hard Drive picture', 'SDD Hard Drive picture', 'Extra storage for your files', 4),
('Desktop Computer', 'Chatham-Kent, ON', 2000, false, 'Desktop Computer picture', 'Desktop Computer picture', 'Desktop Computer picture', 'Desktop Computer picture', 'Has a 4090 TI that has not yet caught on fire!', 4),
('Xbox Controller', 'Chatham-Kent, ON', 900, false, 'Xbox Controller picture', 'Xbox Controller picture', 'Xbox Controller picture', 'Xbox Controller picture', 'Vintage Xbox Controller', 4),
('PS5 Controller', 'Calgary, AB', 500, true, 'PS5 Controller picture', 'PS5 Controller picture', 'PS5 Controller picture', 'PS5 Controller picture', 'The pad and the thumbstick still works!', 5),
('Nintendo Wii', 'Calgary, AB', 1500, true, 'Nintendo Wii picture', 'Nintendo Wii picture', 'Nintendo Wii picture', 'Nintendo Wii picture', 'A classic and is still working!', 5),
('PS5', 'Calgary, AB', 2500, true, 'PS5 picture', 'PS5 picture', 'PS5 picture', 'PS5 picture', 'Recently bought PS5', 5),
('Laptop', 'Edmonton, AB, ON', 3000, true, 'Laptop picture', 'Laptop picture', 'Laptop picture', 'Laptop picture', 'A working laptop that can run Solidworks for 8 hours straight', 6),
('Guitar', 'Edmonton, AB', 1000, false, 'Guitar picture', 'Guitar picture', 'Guitar picture', 'Guitar picture', 'A very sharp scissors', 6),
('Mic Stand', 'Edmonton, AB', 900, true, 'Mic Stand picture', 'Mic Stand picture', 'Mic Stand picture', 'Mic Stand picture', 'A pen that still has ink on it', 6),
('Charger', 'Vancouver, BC', 800, false, 'Charger picture', 'Charger picture', 'Charger picture', 'Charger picture', 'It has both inches and cm on it', 7),
('Microphone', 'Vancouver, BC', 1800, true, 'Microphone picture', 'Microphone picture', 'Microphone picture', 'Microphone picture', 'Just charge it and your good to go!', 7),
('Nintendo Switch', 'Vancouver, BC', 2000, true, 'Nintendo Switch picture', 'Nintendo Switch picture', 'Nintendo Switch picture', 'Nintendo Switch picture', 'Brand new Ipad', 7),
('Portable Heater', 'Regina, SK', 1500, true, 'Portable Heater picture', 'Portable Heater picture', 'Portable Heater picture', 'Portable Heater picture', 'A high-quality speakers', 8),
('3D Printer', 'Regina, SK', 3000, false, '3D Printer picture', '3D Printer picture', '3D Printer picture', '3D Printer picture', 'Amazing calculator that has a Sine, Cosine, and Tan buttons', 8),
('Mechanical Keyboard', 'Regina, SK', 1500, false, 'Mechanical Keyboard picture', 'Mechanical Keyboard picture', 'Mechanical Keyboard picture', 'Mechanical Keyboard picture', 'Good for extra battery during hikes', 8),
('E-Reader', 'Winnipeg, MB', 1700, false, 'E-Reader picture', 'E-Reader picture', 'E-Reader picture', 'E-Reader picture', 'Extra storage for your files', 9),
('Label Maker', 'Winnipeg, MB', 1300, true, 'Label Maker picture', 'Label Maker picture', 'Label Maker picture', 'Label Maker picture', 'Has a 4090 TI that has not yet caught on fire!', 9),
('Lamp', 'Winnipeg, MB', 800, false, 'Lamp picture', 'Lamp picture', 'Lamp picture', 'Lamp picture', 'Vintage Xbox Controller', 9),
('Mouse', 'Killarney, MB', 600, false, 'Mouse picture', 'Mouse picture', 'Mouse picture', 'Mouse picture', 'The pad and the thumbstick still works!', 10),
('Camera', 'Killarney, MB', 300, false, 'Camera picture', 'Camera picture', 'Camera picture', 'Camera picture', 'A classic and is still working!', 10),
('Industrial Fan', 'Killarney, MB', 2000, false, 'Industrial Fan picture', 'Industrial Fan picture', 'Industrial Fan picture', 'Industrial Fan picture', 'Recently bought PS5', 10),
('Bostitch Red Stapler', 'Mississauga, ON', 500, false, 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Stapler picture', 'With One-Finger Stapling Technology by PaperPro, all it takes is a finger to get the job done. The long-lasting sleek, die-cast metal body provides the eye candy your desk craves. The easy stapling of up to 20 sheets along with the ergonomic non-slip comfort grip and base, provide the luxury you deserve. Using standard staples, it also works jam-free and opens for bulletin board tacking. Perfect for home, school, or the office experience a better way to staple.', 3),
('Bostitch Long Grey Stapler', 'Vancouver, BC', 750, false, 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Deli long reach stapler, maximum stapling depth is 12'', perfect choice for binding books, pamphlets, brochures, or card mounting. All metal stapler is designed for durability. Stapler uses regular size staples, 1/4'' (24/6 or 26/6), and has 25 sheets of regular paper stapling capacity.', 5),
('Bostitch Black Grey Stapler', 'Vancouver, BC', 750, false, 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Deli long reach stapler, maximum stapling depth is 12'', perfect choice for binding books, pamphlets, brochures, or card mounting. All metal stapler is designed for durability. Stapler uses regular size staples, 1/4'' (24/6 or 26/6), and has 25 sheets of regular paper stapling capacity.', 5),
('CocomK Blue Plier Hand-held Stapler', 'Calgary, AB', 400, false, 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Powerful hand-held stapler holds 20 sheets stapling capacity at a time. Also work perfect to staple on hardboard, cardbaod, plastic bag, brown paper and any other hard paper. Meets all the daily office and home use needs and work for long lasting high frequency use.', 7),
('Fockety Green Hand-held Stapler', 'Calgary, AB', 400, false, 'Stapler picture', 'Stapler picture', 'Stapler picture', 'Stapler picture', 'This stapler can easily determine the binding position, ergonomic handle is comfortable to grip and convenient for one-handed operation. Safe and environmentally friendly stapleless stapler, a new concept in the field of staplers, you can use in any occasion, and children do not have to worry about hurting their hands.', 9),
('Scriveiner Pen', 'Milton, ON', 150, false, 'Pen picture', 'Pen picture', 'Pen picture', 'Pen picture', 'These fresh, elegant, reliable forest series fountain pen by Asvine is a true marriage of the sophistication of finer days with the latest technology of modern times. Hand assembled and checked for flawless quality, it gives high precision and exceptional writing comfort for every occasion, coupled with a gorgeous design. With this pen in your possession, clients, colleagues, and friends will know you for your taste, class, and sophistication.', 4),
('Novium Hoverpen 2.0', 'Oakville, ON', 350, false, 'Pen picture', 'Pen picture', 'Hoverpen 2.0 was designed to function and to impress. Highly precise craftsmanship of the pedestal has the Hoverpen sitting in a ring of magnetic repulsion. Balancing against at a 23.5 degree angle, the pen itself is engineered to take a stand against gravity itself. The way it defies gravity makes it impossible to ignore.', 6),
('Mileseey Laser Measuring Tape', 'Edmonton, AB', 200, false, 'Measuring Tape picture', 'Measuring Tape picture', 'Measuring Tape picture', 'Measuring Tape picture', 'Laser distance extends to 229ft. MiLESEEY laser measuring tape generates a point/dot that is up to 3X brighter than red beams. This digital tape measure with green-beam allows you to measure in long distance even in super bright days, easy to see and measure, becomes an easy one-man task. Soft and safe to eyes: laser class: Class 2, laser type: 490-560nm, <1mW.', 10),
('Brown Tape Measure', 'Regina, SK', 200, false, 'Measuring Tape picture', 'Measuring Tape picture', 'Measuring Tape picture', 'Measuring Tape picture', '60-Inch sewing tape measure is lightweight and accurately printed in both inches and centimeters, squeeze retractable, Small Leather tape measure very comfortable in the PALM of the Hand, Perfect for sewing, body measuring, fabric measuring and more.', 8),
('Herb Kitchen Scissors', 'Winnipeg, MB', 400, false, 'Scissors picture', 'Scissors picture', 'Scissors picture', 'Scissors picture', 'Monochef herb mincer, made of food grade stainless steel, 5 sharp blades fixed firmly by 3 rivets, durable and safe. Just 1 pair of scissors but installed 5 pairs of blades working at the same time, makes chopping easier and much more efficient than a knife or single blade scissors. Sharp blades make fast leaves snipping rather than crushing or messing. Guarantee no flavor losing of ingredients.', 3),
('Sewing Scissors', 'Winnipeg, MB', 600, false, 'Scissors picture', 'Scissors picture', 'Scissors picture', 'Scissors picture', 'Our versatile right hand scissors heavy duty is made from industrial grade materials –Premium High Carbon Steel- which is stronger, harder and stays sharp longer than the standard stainless steel used in other so called high quality shears. Each blade is durable, solid and has Razor Edge Retention that helps it stays sharp, even after running through the toughest materials, fabrics and leather.', 5);

INSERT INTO reservations (guest_id, item_id, rsrv_start_date, rsrv_end_date, rsrv_date_returned, rsrv_price_bid, rsrv_approval) VALUES
(2, 1, '2022-11-18', '2022-11-25', '2022-11-25', 800, true),
( null, 2, null, null, null, 800, false),
(5, 3, '2022-11-19', '2022-11-27', '2022-11-27', 500, true),
(10, 4, '2022-11-17', '2022-11-19', '2022-11-19', 600, true),
(3, 5, '2022-11-14', '2022-11-21', '2022-11-22', 200, true),
(7, 6, '2022-11-15', '2022-11-25', '2022-11-25', 1200, true),
(4, 7, '2022-11-18', '2022-11-23', '2022-11-23', 700, true),
(10, 8, '2022-11-19', '2022-11-21', '2022-11-21', 500, true),
( null, 9, null, null, null, 1300, true),
( null, 10, null, null, null, 900, false),
( null, 11, null, null, null, 500, true),
( null, 12, null, null, null, 400, true),
(2, 13, '2022-11-20', '2022-11-21', '2022-11-23', 600, true),
(1, 14, '2022-11-20', '2022-11-26', '2022-11-26', 900, true),
(7, 15, '2022-11-19', '2022-11-21', '2022-11-21', 1000, true),
(10, 16, '2022-11-19', '2022-11-21', '2022-11-21', 300, true),
( null, 17, null, null, null, 500, false),
(7, 18, '2022-11-17', '2022-11-22', '2022-11-22', 400, true),
( null, 19, null, null, null, 700, true),
(1, 20, '2022-11-19', '2022-11-27', '2022-11-27', 700, true),
(2, 21, '2022-11-18', '2022-11-25', '2022-11-25', 500, true),
(2, 22, '2022-11-19', '2022-11-27', '2022-11-27', 900, true),
( null, 23, null, null, null, 500, true),
( null, 24, null, null, null, 700, false),
( null, 25, null, null, null, 600, true),
(8, 26, '2022-11-15', '2022-11-19', '2022-11-19', 900, true),
( null, 27, null, null, null, 400, false),
( null, 28, null, null, null, 500, true),
( null, 29, null, null, null, 600, true),
( null, 30, null, null, null, 900, false);

INSERT INTO user_reviews (guest_id, owner_id, item_id, rent_worthy, rent_message )
VALUES 
(1, 6, 16, 9, 'This person sent the item in the actual end date in good condition!'),
(1, 5, 13, 3, 'Returned the item immediately but in a slightly bad condition.'),
(1, 4, 10, 10, '10/10 would allow this person trustworthy'),
(1, 6, 17, 8, 'The guitar string broke but they replaced it when they gave it back'),
(1, 9, 25, 7, 'They returned the item in a good condition!'),
(2, 3, 8, 2, 'The button of the plus sign isnt working correctly when they renturned it!'),
(2, 8, 22, 9, 'My heater was returned in good condition!'),
(2, 1, 1, 9, 'They put their at most respect on the stapler!'),
(2, 10, 29, 7, 'There was a scratch on the side of my Camera'),
(3, 2, 5, 9, 'They refilled the lighter when they returned it'),
(3, 8, 24, 8, 'They took care of my keyboard!'),
(3, 7, 21, 1, 'They returned my Switch with a huge scratch on the screen!');


INSERT INTO item_reviews (guest_id, item_id, item_rating, item_message) 
VALUES 
(3, 1, 4, 'This stapler was springy!'),
(5, 1, 2, 'Pretty bad when I used it!'),
(4, 1, 3, 'It was mid'),
(10, 1, 5, 'I helped Elon Musk acquiring Twitter. I used this Stapler to finalize acquiring it!'),
(8, 1, 5, '5/5 would rent it again'),
(5, 4, 3, 'The tape measure was mid when I used it'),
(1, 4, 3, 'The tape measure was mid when I used it'),
(2, 4, 3, 'The tape measure was mid when I used it'),
(6, 4, 3, 'The tape measure was mid when I used it'),
(5, 7, 1, 'The Speakers was cutting out and had to reset the bluetooth connection often'),
(7, 7, 3, 'The Speakers was mid'),
(9, 7, 4, 'The Speakers was good');