INSERT INTO users (user_name, user_email, user_password, user_image)
VALUES
('Sylvia Palmer', 'spalmer@gmail.com', '12345', 'https://i.imgur.com/LpaY82x.png'),
('Terrence Malcolm', 'tmalcolm@gmail.com', '12345', 'https://i.imgur.com/Nmx0Qxo.png'),
('Mildred Nazir', 'mnazir@gmail.com', '12345', 'https://i.imgur.com/T2WwVfS.png'),
('Charles Roy', 'croy@gmail.com', '12345', 'https://i.imgur.com/FK8V841.jpg'),
('Sven Jones', 'sjones@gmail.com', '12345', 'https://i.imgur.com/twYrpay.jpg'),
('Susan Reynolds', 'sreynolds@gmail.com', '12345', 'https://i.imgur.com/TdOAdde.jpg'),
('Alec Quon', 'aquon@gmail.com', '12345', 'https://i.imgur.com/3tVgsra.jpg'),
('Viktor Jain', 'vjain@gmail.com', '12345', 'https://i.imgur.com/iHq8K8Z.jpg'),
('Liam Chu', 'lchu@gmail.com', '12345', 'https://i.imgur.com/nPywAp1.jpg'),
('Sam Stanic', 'sstanic@gmail.com', '12345', 'https://i.imgur.com/okB9WKC.jpg');

INSERT INTO items (item_name, item_location, item_base_price, item_status, item_image, item_description, owner_id) 
VALUES 
('Swingline Stapler', 'Milton, ON', 4.5, true, 'https://i.imgur.com/j1zKeiV.jpg', 'LightTouch Reduced Effort Stapler simplifies stapling two to 20 sheets. Stapler is engineered for smooth, easy operation, and excels at low sheet counts. For best performance, use Swingline S.F. 4 Premium Staples. Full-strip stapler design accommodates full strip of 210 staples. Soft grip surfaces enhance feel and control for desktop or handheld use. Made with a durable plastic housing and metal mechanism.', 1),
('Multifunctional Kitchen Scissors', 'Milton, ON', 5, false, 'https://i.imgur.com/XrT3T6h.jpg', 'Kitchen scissors are made of high-quality 3CR14 stainless steel, corrosion resistant, really sharp and durable, for cutting meat, chicken, poultry, fruits, fish scale, vegetables, herbs and so on', 1),
('Asvine Pen', 'Milton, ON', 1.5, true, 'https://i.imgur.com/5lajyp1.jpg', 'These fresh, elegant, reliable forest series fountain pen by Asvine is a true marriage of the sophistication of finer days with the latest technology of modern times. Hand assembled and checked for flawless quality, it gives high precision and exceptional writing comfort for every occasion, coupled with a gorgeous design. With this pen in your possession, clients, colleagues, and friends will know you for your taste, class, and sophistication.', 1),
('Craftsman Measuring Tape', 'Vancouver, BC', 2, false, 'https://i.imgur.com/7zAhSsz.jpg', 'Measure twice, cut once, and rely on Craftsman tapes for fast and accurate measurements. Our self lock tape measures feature blades that automatically stay in a locked position until you press a button to retract them. The auto-locking feature offers smooth, comfortable retraction to avoid having the hook slam into the case, which makes the tapes both user friendly and longer lasting. Fractions are printed on the blade to make taking measurements easier than ever before, making this the perfect tape measure for new homeowners or avid DIYers.', 2),
('Rechargeable Candle Lighter', 'Vancouver, BC', 2, true, 'https://i.imgur.com/O89MaaH.jpg', 'Our lighters can not only be matched with candles, gas stoves and hot stoves, but also can be used as camping lighters, fireworks lighters, fire lighters and barbecue lighters. It can be used not only indoors, but also outdoors in bad weather. It is windproof and moisture-proof. It is a must-have item for indoor and outdoor activities.', 2),
('Ipad 11" 2022', 'Vancouver, BC', 15, true, 'https://i.imgur.com/1kVQkog.jpg', 'Brilliant 11-inch Liquid Retina display with ProMotion, True Tone, and P3 wide color, M2 chip with 8-core CPU and 10-core GPU, 12MP Wide camera, 10MP Ultra Wide back camera, and LiDAR Scanner for immersive AR, 12MP Ultra Wide front camera with Center Stage, Go far with all-day battery life!', 2),
('Logitech Z150 Speakers', 'Couborg, ON', 7, true, 'https://i.imgur.com/XkHp8gQ.jpg', 'Rich stereo sound: Two 2-"drivers deliver 6 watts of peak power for clear, loud stereo sound. Connect two devices at the same time: Simultaneously connect your smartphone plus tablet or laptop via a 3.5mm audio input plus auxiliary line.', 3),
('Scientific LCD Calculator 2022', 'Couborg, ON', 4, true, 'https://i.imgur.com/PWjeueQ.jpg','Calculators and notepad are designed in one, you can take notes while calculating, improving study and work efficiency. The engineering calculator supports up to 10 digital calculations, the numbers are clear and readable, suitable for advanced and beginners.', 3),
('Solar Charger Battery Bank', 'Couborg, ON', 7, false, 'https://i.imgur.com/GTEHqIJ.jpg', 'Built-in 26800mAh high capacity polymer battery equipped with a compact solar panel, which could recharge the battery itself under sunlight, eco-friendly and ideal for outdoor activity.', 3),
('Portable Samsung SDD Hard Drive', 'Chatham-Kent, ON', 4, false, 'https://i.imgur.com/QReMfxR.jpg', 'Samsung Portable SSD T7 Shieldis a rubber protected external storage device for outdoor users, and contents creators which features outstanding performanceand strengthened durability. The T7 Shield earns consumer trust with its high compatibility', 4),
('Cyberpower Gamer Desktop Computer', 'Chatham-Kent, ON', 20, false, 'https://i.imgur.com/NQYEMfa.jpg', 'Get the pinnacle of gaming performance with the CYBERPOWERPC Gamer Supreme series of gaming computers. The Gamer Supreme series features monstrous processing power combined with the latest and greatest graphics cards to handle even the most demanding games on the market. An immense RAM allows you to easily tackle system-intensive applications such as video editing, and ensures a lag-free multitasking experience.', 4),
('Xbox Controller', 'Chatham-Kent, ON', 9, false, 'https://i.imgur.com/ctR9hqm.jpg', 'Wireless 2.4G connection, exclusive frequency hopping technology, powerful anti-interference ability, stable connection signal, and free control. Lets you play games happily in the living room and bedroom. No wires, no mess, just wirelessly connect to your device to play games. The wireless controller does not have a headphone jack.', 4),
('PS5 Controller', 'Calgary, AB', 5, true, 'https://i.imgur.com/IqUaCJT.jpg', 'Turn your existing controller for PS5 into a professional eSport elite controller. Only compatible with PS5 Controller BDM-010, NOT fit for BDM-020 controller and other controller!', 5),
('Nintendo Wii', 'Calgary, AB', 15, true, 'https://i.imgur.com/KS6z2Is.jpg', 'Netflix instant streaming functionality allows for thousands of movies, TV shows, cartoons and more right on your TV Bundle contents including Wii Sports Resort and the Wii MotionPlus accessory!', 5),
('PS5: Horizon Zero Dawn Edition', 'Calgary, AB', 75, true, 'https://i.imgur.com/xj4LfNx.jpg', 'What is in the Box: PlayStation 5 console; DualSense wireless controller; DualSense USB charging cable; Horizon Forbidden West full game voucher; ASTROs PLAYROOM (Pre-installed game); Base; HDMI cable; AC power cord; Printed materials.', 5),
('Dell XPS 17" 9700 Laptop', 'Calgary, AB', 100, true, 'https://i.imgur.com/EQHgAMl.jpg', 'Desktop-caliber creativity in a laptop:Packed with staggering performance typically only available from desktops, 10th Gen Intel Core processors bring desktop-caliber creativity to your laptop.', 6),
('Jasmin Classic Guitar', 'Calgary, AB', 10, false, 'https://i.imgur.com/or1yMkM.jpg', 'Gloss natural, Gloss natural, Dreadnought body style, Laminate spruce top, Sapele back and sides; Inlays: Pearloid Dots', 6),
('Tripod Gooseneck Mic Stand', 'Calgary, AB', 9, true, 'https://i.imgur.com/rdHeX9B.jpg', 'The microphone floor-mounted tripod is suitable for stage performances,karaoke concerts,speeches,conference rooms,parties,online courses,weddings or live broadcasts,etc.Foldable and disassembled,no need to take up space,and make it easy to set up and transport.', 6),
('INUI Wireless Charger', 'Vancouver, BC', 8, false, 'https://i.imgur.com/om0Stap.jpg', 'Features the first-seen self-adaptive LED indicator to bright in the day and dim in the dark. So you will stay in the know yet without undesirable lights to disturb your sleep.', 7),
(' Blue Yeti Microphone', 'Vancouver, BC', 18, true, 'https://i.imgur.com/OGCexjv.jpg', 'Custom Three-Capsule Array: Produces clear, powerful, broadcast-quality sound for YouTube, game streaming, podcasting, Zoom calls and music!', 7),
('Nintendo Switch', 'Vancouver, BC', 20, true, 'https://i.imgur.com/Cq4knsB.jpg', '7-Inch OLED screen - Enjoy vivid colors and crisp contrast with a screen that makes colors pop. Wide adjustable Stand - freely angle the systems wide, adjustable Stand for comfortable viewing in tabletop mode.', 7),
('Portable Electic Heater', 'Winnipeg, MB', 15, true, 'https://i.imgur.com/cKuXR0D.jpg', '2 in 1 Heater Fan: This ceramic heater provides two heat levels (1500W/750W) and one cool air (fan), you can use it both for winter and summer. Thermostat control of the heater will turn the heater off when it reaches a preset temperature and turn the heater back on when the temperature dips below the thermostat setting.', 8),
('Snapmaker 2.0 3D Printer', 'Winnipeg, MB', 150, false, 'https://i.imgur.com/fJ7a7Mo.jpg', 'Larger Work Area&Upgraded Cooling System: F350 3D Printers offers a larger work area of 320*350*330mm, which is capable of making much bigger prints or multiple smaller objects in one go. The cooling system of F350 is upgraded to combine fast speed and brilliant accuracy at the same time. You can now 3D print larger projects even faster.', 8),
('Havit Mechanical Keyboard', 'Winnipeg, MB', 15, false, 'https://i.imgur.com/zA3wBCp.jpg', 'Compact Keyboard with Numpad Unlike bulky full-sized layout, this 85% keyboard saves more desk space but keep the numkeys which is essential. Press Fn+Backspace to lock/unlock the numkeys.', 8),
('Kobo Elipsa E-Reader', 'Winnipeg, MB', 17, false, 'https://i.imgur.com/zA3wBCp.jpg', 'Includes the Kobo Elipsa eReader, Kobo Stylus, and SleepCover. The Kobo Stylus lets you write directly on the page, just like a pen on paper. The SleepCover is designed to stand at the optimum height for writing and reading, and puts your eReader to sleep when you close it.', 9),
('Dymo Label Maker', 'Winnipeg, MB', 13, true, 'https://i.imgur.com/C3GBdOW.jpg', 'Compact and lightweight for portability, making it easy to label just about anything, anywhere, Label maker lets you quickly type text on the familiar computer-style QWERTY keyboard, edit with one-touch fast-formatting keys and print perfect, professional labels every time, Enjoy extended battery life with automatic switch-off.', 9),
('Rechargeable LED Flaslight, 90,000 Lumens', 'Winnipeg, MB', 8, false, 'https://i.imgur.com/P3cOGZ0.jpg', 'This flashlight has a built-in advanced XHP90 LED chip for a maximum output of up to 90000 lumens. Rechargeable flashlight can light up the road and things within 1650ft. This LED flashlight has a high-quality life of up to 15 hours and over 100,000 hours lifespan.', 9),
('Logitech MX Master 3S Mouse', 'Killarney, MB', 6, false, 'https://i.imgur.com/GStjC8L.jpg', 'Ergonomic design: Work comfortably with a precision mouse featuring a silhouette crafted for a more natural wrist posture and optimally placed thumb controls!', 10),
('Canon EOS Rebel  DSLR Camera', 'Killarney, MB', 3, false, 'https://i.imgur.com/jgv6Efk.jpg', 'No matter where your next adventure takes you, count on the EOS Rebel T7s impressive 24.1 Megapixel CMOS sensor and wide ISO range of 100-6400 (H: 12800) to capture high-quality images, even in low-light situations.', 10),
('Simple Deluxe 20" Industrial Fan', 'Killarney, MB', 20, false, 'https://i.imgur.com/nvzlQ24.jpg', 'This super wall fan has create an air velocity of 4, 650 CFM. Reinforced wire grill for added safety. All-metal construction with aluminum blades make these fans as a good choice at workshops, basements, living rooms and garages.', 10),
('Bostitch Red Stapler', 'Coubourg, ON', 5, false, 'https://i.imgur.com/kFxYIc0.jpg', 'With One-Finger Stapling Technology by PaperPro, all it takes is a finger to get the job done. The long-lasting sleek, die-cast metal body provides the eye candy your desk craves. The easy stapling of up to 20 sheets along with the ergonomic non-slip comfort grip and base, provide the luxury you deserve. Using standard staples, it also works jam-free and opens for bulletin board tacking. Perfect for home, school, or the office experience a better way to staple.', 3),
('Deli Long Grey Stapler', 'Calgary, AB', 7.5, false, 'https://i.imgur.com/RZ317G2.jpg', 'Deli long reach stapler, maximum stapling depth is 12'', perfect choice for binding books, pamphlets, brochures, or card mounting. All metal stapler is designed for durability. Stapler uses regular size staples, 1/4'' (24/6 or 26/6), and has 25 sheets of regular paper stapling capacity.', 5),
('Bostitch Black Grey Stapler', 'Calgary, AB', 7.5, false, 'https://i.imgur.com/8sk9Qgg.jpg', 'Deli long reach stapler, maximum stapling depth is 12'', perfect choice for binding books, pamphlets, brochures, or card mounting. All metal stapler is designed for durability. Stapler uses regular size staples, 1/4'' (24/6 or 26/6), and has 25 sheets of regular paper stapling capacity.', 6),
('CocomK Blue Plier Hand-held Stapler', 'Vancouver, BC', 4, false, 'https://i.imgur.com/rDu69i5.jpg', 'Powerful hand-held stapler holds 20 sheets stapling capacity at a time. Also work perfect to staple on hardboard, cardbaod, plastic bag, brown paper and any other hard paper. Meets all the daily office and home use needs and work for long lasting high frequency use.', 7),
('Fockety Green Hand-held Stapler', 'Winnipeg, MB', 4, false, 'https://i.imgur.com/qCiojiu.jpg', 'This stapler can easily determine the binding position, ergonomic handle is comfortable to grip and convenient for one-handed operation. Safe and environmentally friendly stapleless stapler, a new concept in the field of staplers, you can use in any occasion, and children do not have to worry about hurting their hands.', 9),
('Scriveiner Pen', 'Chatham-Kent, ON', 1.5, false, 'https://i.imgur.com/oyYJgSi.jpg', 'These fresh, elegant, reliable forest series fountain pen by Asvine is a true marriage of the sophistication of finer days with the latest technology of modern times. Hand assembled and checked for flawless quality, it gives high precision and exceptional writing comfort for every occasion, coupled with a gorgeous design. With this pen in your possession, clients, colleagues, and friends will know you for your taste, class, and sophistication.', 4),
('Novium Hoverpen 2.0', 'Calgary, AB', 3.5, false, 'https://i.imgur.com/g4pnPmG.jpg', 'Hoverpen 2.0 was designed to function and to impress. Highly precise craftsmanship of the pedestal has the Hoverpen sitting in a ring of magnetic repulsion. Balancing against at a 23.5 degree angle, the pen itself is engineered to take a stand against gravity itself. The way it defies gravity makes it impossible to ignore.', 6),
('Mileseey Laser Measuring Tape', 'Killarney, MB', 2, false, 'https://i.imgur.com/uGcDivx.jpg', 'Laser distance extends to 229ft. MiLESEEY laser measuring tape generates a point/dot that is up to 3X brighter than red beams. This digital tape measure with green-beam allows you to measure in long distance even in super bright days, easy to see and measure, becomes an easy one-man task. Soft and safe to eyes: laser class: Class 2, laser type: 490-560nm, <1mW.', 10),
('Brown Tape Measure', 'Winnipeg, MB', 2, false, 'https://i.imgur.com/bq0xryx.jpg', '60-Inch sewing tape measure is lightweight and accurately printed in both inches and centimeters, squeeze retractable, Small Leather tape measure very comfortable in the PALM of the Hand, Perfect for sewing, body measuring, fabric measuring and more.', 8),
('Herb Kitchen Scissors', 'Coubourg, ON', 4, false, 'https://i.imgur.com/4WSrQhp.jpg', 'Monochef herb mincer, made of food grade stainless steel, 5 sharp blades fixed firmly by 3 rivets, durable and safe. Just 1 pair of scissors but installed 5 pairs of blades working at the same time, makes chopping easier and much more efficient than a knife or single blade scissors. Sharp blades make fast leaves snipping rather than crushing or messing. Guarantee no flavor losing of ingredients.', 3),
('Sewing Scissors', 'Calgary, AB', 6, false, 'https://i.imgur.com/L3a3GlQ.jpg', 'Our versatile right hand scissors heavy duty is made from industrial grade materials Premium High Carbon Steel which is stronger, harder and stays sharp longer than the standard stainless steel used in other so called high quality shears. Each blade is durable, solid and has Razor Edge Retention that helps it stays sharp, even after running through the toughest materials, fabrics and leather.', 5),
('Butane Lighter', 'Milton, ON', 1.5, false, 'https://i.imgur.com/zAkvIEu.jpg', 'Single Power Torch More Powerful,Cool and Stylish..Visible Fuel Tank Let you know when to refill and when is full.Flame Regulator Rotate the bottom to adjust the size of the flame. Simple and Easy to operate!', 1),
('Ipad 9.7" 2017', 'Coubourg, ON', 10, false, 'https://i.imgur.com/PmogLoK.jpg', 'Brilliant 11-inch Liquid Retina display with ProMotion, True Tone, and P3 wide color, M2 chip with 8-core CPU and 10-core GPU, 12MP Wide camera, 10MP Ultra Wide back camera, and LiDAR Scanner for immersive AR, 12MP Ultra Wide front camera with Center Stage, Go far with all-day battery life!', 3),
('Edifier R1280T Speakers', 'Calgary, AB', 7, false, 'https://i.imgur.com/npT141p.jpg', 'The R1280T powered bookshelf speakers has combined a retro look with a modern sense of audio quality. If you are looking for affordable and versatile bookshelf speakers with uncompromising sound the R1280T bookshelf speakers is your go-to 2.0 speaker system. ', 5),
('PS5: God of War Ragnarok Edition', 'Calgary, AB', 80, false, 'https://i.imgur.com/71xSwCu.jpg', 'Bundle includes: PlayStation 5 console, DualSense Wireless Controller, Base, HDMI Cable, AC power cord, USB cable, God of War Ragnarok full game voucher.', 6),
('Nintendo Switch Lite', 'Vancouver, BC', 18, true, 'https://i.imgur.com/ZNjNBn9.jpg', 'Optimized for personal, handheld play, Nintendo Switch lite is a small and light Nintendo Switch system. For every member of your family, there is a member of ours. Compatible with all physical and digital Nintendo Switch Games that support handheld mode.', 2),
('Snapmaker J1 3D Printer', 'Winnipeg, MB', 125, false, 'https://i.imgur.com/1aD0C6m.jpg', 'Say hello to Jadelabo J1, a powerful 3D printer designed for makers and creators. With two independent print heads, you can speed up the printing by 2X, or print two different materials in one single object. Even better, it has the easiest calibration, the ecosystem with software and support, and all the smart features we expect from an easy-to-use IDEX 3D printer. It will come fully assembled and tested by the professionals at our team. ', 8);

INSERT INTO reservations (guest_id, item_id, rsrv_start_date, rsrv_end_date, rsrv_date_returned, rsrv_price_bid, rsrv_approval) VALUES
(2, 1, '2022-11-18', '2022-11-25', '2022-11-25', 800, 'pending'),
( null, 2, null, null, null, 800, 'pending'),
(5, 2, '2022-11-19', '2022-11-27', '2022-11-27', 500, 'pending'),
(10, 4, '2022-11-17', '2022-11-19', '2022-11-19', 600, 'pending'),
(3, 5, '2022-11-14', '2022-11-21', '2022-11-22', 200, 'pending'),
(7, 5, '2022-11-15', '2022-11-25', '2022-11-25', 1200, 'pending'),
(4, 7, '2022-11-18', '2022-11-23', '2022-11-23', 700, 'pending'),
(10, 8, '2022-11-19', '2022-11-21', '2022-11-21', 500, 'pending'),
( null, 5, null, null, null, 1300, 'pending'),
( null, 10, null, null, null, 900, 'pending'),
( null, 11, null, null, null, 500, 'pending'),
( null, 12, null, null, null, 400, 'pending'),
(2, 13, '2022-11-20', '2022-11-21', '2022-11-23', 600, 'pending'),
(1, 14, '2022-11-20', '2022-11-26', '2022-11-26', 900, 'pending'),
(7, 15, '2022-11-19', '2022-11-21', '2022-11-21', 1000, 'pending'),
(10, 16, '2022-11-19', '2022-11-21', '2022-11-21', 300, 'pending'),
( null, 17, null, null, null, 500, 'pending'),
(7, 18, '2022-11-17', '2022-11-22', '2022-11-22', 400, 'pending'),
( null, 19, null, null, null, 700, 'pending'),
(1, 20, '2022-11-19', '2022-11-27', '2022-11-27', 700, 'pending'),
(2, 21, '2022-11-18', '2022-11-25', '2022-11-25', 500, 'pending'),
(2, 22, '2022-11-19', '2022-11-27', '2022-11-27', 900, 'pending'),
( null, 23, null, null, null, 500, 'pending'),
( null, 24, null, null, null, 700, 'pending'),
( null, 25, null, null, null, 600, 'pending'),
(8, 26, '2022-11-15', '2022-11-19', '2022-11-19', 900, 'pending'),
( null, 27, null, null, null, 400, 'pending'),
( null, 28, null, null, null, 500, 'pending'),
( null, 29, null, null, null, 600, 'pending'),
( null, 30, null, null, null, 900, 'pending');

INSERT INTO user_reviews (guest_id, owner_id, item_id, rent_worthy, rent_message )
VALUES 
(1, 6, 16, 9, 'This person sent the item in the actual end date in good condition!'),
(1, 5, 13, 3, 'Returned the item immediately but in a slightly bad condition.'),
(1, 4, 10, 10, '10/10 would allow this person trustworthy'),
(1, 6, 17, 8, 'The guitar string broke but they replaced it when they gave it back'),
(1, 9, 25, 7, 'They returned the item in a good condition!'),
(2, 3, 8, 2, 'The button of the plus sign isnt working correctly when they renturned it!'),
(2, 8, 22, 9, 'My heater was returned in good condition!'),
(2, 1, 1, 9, 'They put their at most respect on the stapler!'),
(2, 10, 29, 7, 'There was a scratch on the side of my Camera'),
(3, 2, 5, 9, 'They refilled the lighter when they returned it'),
(3, 8, 24, 8, 'They took care of my keyboard!'),
(3, 7, 21, 1, 'They returned my Switch with a huge scratch on the screen!');


INSERT INTO item_reviews (guest_id, item_id, item_rating, item_message) 
VALUES 
(3, 1, 4, 'This stapler was springy!'),
(5, 1, 2, 'Pretty bad when I used it!'),
(4, 1, 3, 'It was mid'),
(10, 1, 5, 'I helped Elon Musk acquiring Twitter. I used this Stapler to finalize acquiring it!'),
(8, 1, 5, '5/5 would rent it again'),
(5, 4, 3, 'The tape measure was mid when I used it'),
(1, 4, 3, 'The tape measure was mid when I used it'),
(2, 4, 3, 'The tape measure was mid when I used it'),
(6, 4, 3, 'The tape measure was mid when I used it'),
(5, 7, 1, 'The Speakers was cutting out and had to reset the bluetooth connection often'),
(7, 7, 3, 'The Speakers was mid'),
(9, 7, 4, 'The Speakers was good');